<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\background.png" />
    <None Remove="Assets\coin.png" />
    <None Remove="Assets\interest-rate.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Downloads\coin.png" Link="Assets\coin.png" />
    <Content Include="..\..\..\..\Downloads\interest-rate.png" Link="Assets\interest-rate.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\background.png" />
    <Resource Include="Assets\coin.png" />
    <Resource Include="Assets\interest-rate.png" />
  </ItemGroup>

</Project>
